In [2]:
import numpy as np

In [3]:
a=np.random.randn(10)  #random number array

In [4]:
a

array([-1.35509969, -1.43019018, -0.36936474,  0.80126116,  0.61713728,
        1.01692238,  0.41609073,  2.35586261, -0.04124185,  1.71834955])

In [5]:
b=np.random.randn(10)   #random number array

In [6]:
b

array([ 0.39811569, -1.85773842,  0.23051842, -0.20957375,  0.9558539 ,
       -0.30408469, -0.3811565 ,  0.57801172,  0.49644738, -0.18300695])

In [7]:
a+b

array([-0.956984  , -3.2879286 , -0.13884632,  0.59168741,  1.57299118,
        0.71283769,  0.03493422,  2.93387434,  0.45520553,  1.5353426 ])

In [8]:
a*b

array([-0.53948645,  2.65691924, -0.08514537, -0.1679233 ,  0.58989307,
       -0.30923052, -0.15859569,  1.36171621, -0.02047441, -0.31446991])

In [9]:
a>0

array([False, False, False,  True,  True,  True,  True,  True, False,
        True])

In [10]:
a[a>0]

array([0.80126116, 0.61713728, 1.01692238, 0.41609073, 2.35586261,
       1.71834955])