In [1]:
import numpy as np

In [2]:
x=np.array([10,9,8,7,6])

In [4]:
np.sqrt(x)   # square root

array([3.16227766, 3.        , 2.82842712, 2.64575131, 2.44948974])

In [5]:
np.power(x,2)   # power of x^2

array([100,  81,  64,  49,  36], dtype=int32)

In [6]:
y=[11,10,9,6,5]     # list of y element

In [7]:
np.maximum(x,y)     # compare x,y maximum values

array([11, 10,  9,  7,  6])