In [1]:
import numpy as np

In [2]:
x=[[1,2,3,4],[5,6,7,8]]   # list

In [3]:
arr1=np.array(x)     # convert in array

In [4]:
y=[[9,8,7,6],[5,4,3,2]]   # list

In [5]:
arr2=np.array(y)    # convert in array

In [7]:
np.concatenate((arr1,arr2),axis=0)   # max row wise

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [8]:
np.concatenate((arr1,arr2),axis=1)   # max column wise

array([[1, 2, 3, 4, 9, 8, 7, 6],
       [5, 6, 7, 8, 5, 4, 3, 2]])

In [10]:
np.vstack((arr1,arr2))           # max row wise

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [11]:
np.hstack((arr1,arr2))          # max column wise

array([[1, 2, 3, 4, 9, 8, 7, 6],
       [5, 6, 7, 8, 5, 4, 3, 2]])