In [1]:
import numpy as np

In [2]:
x=[1,2,3,4,5]

In [3]:
y=[6,7,8,9,10]

In [4]:
np.save("testx",x)    #(filename.npy,array)

In [5]:
np.load("testx.npy")   #(filename.npy)

array([1, 2, 3, 4, 5])

In [21]:
np.savez("testxy",x=x,y=y)    #(filename.npy,array1,array2)

In [22]:
loadxy=np.load("testxy.npz")

In [23]:
loadxy

In [25]:
loadxy["x"]

array([1, 2, 3, 4, 5])

In [26]:
loadxy["y"]

array([ 6,  7,  8,  9, 10])