In [1]:
import numpy as np

In [4]:
x=np.array([9,8,7,6,5])

In [5]:
x

array([9, 8, 7, 6, 5])

In [6]:
x[3]

6

In [7]:
x[x>5]

array([9, 8, 7, 6])

In [9]:
x[[2,1]]

array([7, 8])

# Slicing

In [10]:
x=np.random.randn(10,10)

In [11]:
x

array([[ 1.06604243,  0.57543751, -0.59171469, -0.65624166,  2.02421612,
        -0.43010445,  2.08850195, -0.95335408,  1.31138887, -0.03643883],
       [ 0.85706954,  0.63235732, -0.4964655 ,  0.21169175,  0.0445468 ,
         0.50470569,  1.09465049, -0.6215239 ,  0.11814995,  0.6889398 ],
       [-1.42103694,  2.31006435,  1.42566295,  0.34220271, -1.65177507,
         1.15056238,  0.67622872, -1.02173959, -0.2249462 ,  0.68358715],
       [ 1.12751475,  0.65021337,  0.24571962, -0.85542319,  1.17942381,
         1.9865571 , -2.1598774 ,  0.48464647, -0.63105876, -1.00653745],
       [ 0.87414498, -0.49418319, -0.57964634,  0.77068523, -0.83348456,
         0.73042502,  0.489666  , -0.24577534,  0.68978538,  0.08000956],
       [ 1.80839436,  1.47705131, -0.26828626, -1.20328319,  0.26312203,
        -0.04525369, -0.45542622,  1.09655255, -1.46536876, -0.76978391],
       [ 0.24849248,  0.33412739, -2.25586397,  1.20278506,  0.55377478,
         0.28578274,  0.13133332,  0.33232073

In [12]:
x[0]    # first row print

array([ 1.06604243,  0.57543751, -0.59171469, -0.65624166,  2.02421612,
       -0.43010445,  2.08850195, -0.95335408,  1.31138887, -0.03643883])

In [13]:
x[0][4]   # 0 row 4th column

2.024216117506737

In [14]:
x[1:10:2]   # 2 column

array([[ 0.85706954,  0.63235732, -0.4964655 ,  0.21169175,  0.0445468 ,
         0.50470569,  1.09465049, -0.6215239 ,  0.11814995,  0.6889398 ],
       [ 1.12751475,  0.65021337,  0.24571962, -0.85542319,  1.17942381,
         1.9865571 , -2.1598774 ,  0.48464647, -0.63105876, -1.00653745],
       [ 1.80839436,  1.47705131, -0.26828626, -1.20328319,  0.26312203,
        -0.04525369, -0.45542622,  1.09655255, -1.46536876, -0.76978391],
       [-1.03350984,  0.18171233, -0.10207142,  0.6456206 , -1.26024815,
         0.77550058, -0.69971008,  0.18913619, -0.27993213, -0.51584865],
       [-0.27018709,  0.63593094,  1.37782974,  0.16361186,  0.55417598,
         0.07179264, -1.54571732,  1.03493898, -0.1536571 ,  0.26085298]])

In [16]:
x=np.ones((5,5))

In [17]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
x[1:-1,1:-1]=0   # 1 firstrow -1 lastrow and 1 first column -1 lastcolumn   

In [19]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])