In [1]:
import numpy as np

In [2]:
x=np.random.randn(3,2)  # 3 row, 2 column

In [3]:
x

array([[ 0.49579414,  0.4337105 ],
       [-1.66137068, -0.32201513],
       [ 0.87026264,  0.32869976]])

In [5]:
y=np.random.randn(2,3)  # 2 row, 3 column

In [6]:
y

array([[ 1.67657657, -0.67144422, -0.52986181],
       [-0.00304372,  0.51853004, -1.05536286]])

In [7]:
x.dot(y)

array([[ 0.82991673, -0.10800618, -0.72042434],
       [-2.78443503,  0.94854323,  1.22013969],
       [ 1.45806148, -0.41389212, -0.80801646]])

In [8]:
x.transpose()

array([[ 0.49579414, -1.66137068,  0.87026264],
       [ 0.4337105 , -0.32201513,  0.32869976]])

In [9]:
x.trace()

0.17377900654965367