In [1]:
import numpy as np

In [2]:
x=np.random.randn(4,5)

In [3]:
x

array([[ 1.82865009,  1.1726096 , -0.44484355, -0.42523048,  0.38834818],
       [ 0.23356614, -0.24472363,  0.15559659, -0.26545222, -0.27897841],
       [-0.57169567,  0.48773096, -1.40362845,  0.27489986, -0.16198002],
       [-0.46675394,  0.78089206,  0.73257465,  0.42077903, -1.68625404]])

In [5]:
x.reshape(2,2,5)

array([[[ 1.82865009,  1.1726096 , -0.44484355, -0.42523048,
          0.38834818],
        [ 0.23356614, -0.24472363,  0.15559659, -0.26545222,
         -0.27897841]],

       [[-0.57169567,  0.48773096, -1.40362845,  0.27489986,
         -0.16198002],
        [-0.46675394,  0.78089206,  0.73257465,  0.42077903,
         -1.68625404]]])

In [8]:
x.reshape((2,2,5),order="F")

array([[[ 1.82865009,  1.1726096 , -0.44484355, -0.42523048,
          0.38834818],
        [-0.57169567,  0.48773096, -1.40362845,  0.27489986,
         -0.16198002]],

       [[ 0.23356614, -0.24472363,  0.15559659, -0.26545222,
         -0.27897841],
        [-0.46675394,  0.78089206,  0.73257465,  0.42077903,
         -1.68625404]]])

In [9]:
x.reshape(2,2,-1)

array([[[ 1.82865009,  1.1726096 , -0.44484355, -0.42523048,
          0.38834818],
        [ 0.23356614, -0.24472363,  0.15559659, -0.26545222,
         -0.27897841]],

       [[-0.57169567,  0.48773096, -1.40362845,  0.27489986,
         -0.16198002],
        [-0.46675394,  0.78089206,  0.73257465,  0.42077903,
         -1.68625404]]])

In [10]:
x

array([[ 1.82865009,  1.1726096 , -0.44484355, -0.42523048,  0.38834818],
       [ 0.23356614, -0.24472363,  0.15559659, -0.26545222, -0.27897841],
       [-0.57169567,  0.48773096, -1.40362845,  0.27489986, -0.16198002],
       [-0.46675394,  0.78089206,  0.73257465,  0.42077903, -1.68625404]])

In [11]:
x.ravel()

array([ 1.82865009,  1.1726096 , -0.44484355, -0.42523048,  0.38834818,
        0.23356614, -0.24472363,  0.15559659, -0.26545222, -0.27897841,
       -0.57169567,  0.48773096, -1.40362845,  0.27489986, -0.16198002,
       -0.46675394,  0.78089206,  0.73257465,  0.42077903, -1.68625404])

In [12]:
x.flatten()

array([ 1.82865009,  1.1726096 , -0.44484355, -0.42523048,  0.38834818,
        0.23356614, -0.24472363,  0.15559659, -0.26545222, -0.27897841,
       -0.57169567,  0.48773096, -1.40362845,  0.27489986, -0.16198002,
       -0.46675394,  0.78089206,  0.73257465,  0.42077903, -1.68625404])