In [1]:
import numpy as np

In [2]:
x=np.array([10,9,8,10,7])

In [3]:
x

array([10,  9,  8, 10,  7])

In [4]:
x.mean()

8.8

In [5]:
x.cumsum()

array([10, 19, 27, 37, 44], dtype=int32)

In [6]:
x.cumprod()

array([   10,    90,   720,  7200, 50400], dtype=int32)

In [7]:
y=x>6

In [8]:
y

array([ True,  True,  True,  True,  True])

In [9]:
y.sum()   # true= 1

5

In [10]:
y.any()   # koi eak true ho

True

In [11]:
y.all()   # sab true ho

True

In [12]:
y=x>8

In [13]:
y

array([ True,  True, False,  True, False])

In [14]:
y.sum()

3

In [15]:
y.any()

True

In [16]:
y.all()

False

In [17]:
x.sort()   # arrange ho jatey han

In [18]:
x

array([ 7,  8,  9, 10, 10])

In [19]:
np.unique(x)     # repeated element nhi atey

array([ 7,  8,  9, 10])